services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/render-examples/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_ENCRYPTION_SECRET_KEY="NhfbqAty0cmsaAoo5zxNwaPfYrjwFOns" java -jar metabase.jar
        fromDatabase:
          name: stage_38ah
          property: connectionString
databases:
  - name: stage_38ah
    databaseName: stage_38ah
    ipAllowList: [] # only allow internal connections
